# Generated by Django 5.0 on 2023-12-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.FloatField(max_length=6)),
                ('quantity_of_prod', models.IntegerField()),
                ('add_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('user_address', models.TextField()),
                ('register_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_summ', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.user')),
            ],
        ),
    ]
